import os
import numpy as np


def get_txt_data(file_map,state):
    x, y, z = [], [], []
    # 读取txt文件
    # 打开文件
    with open(file_map, 'r') as file:
        # 跳过第一行（无论是否为注释）
        next(file)
        for line in file:
            line = line.strip()  # 去掉行首尾的空格和换行符
            # 新增：跳过以#开头的注释行和空行
            if not line or line.startswith('#'):
                continue
            # 确保行不为空且不是注释
            if line:
                columns = line.split()  # 按空格或制表符分割行
                if len(columns) >= 3:  # 确保行中有至少三列数据
                    x.append(float(columns[0]))  # 提取第一列并转换为浮点数
                    y.append(float(columns[1]))  # 提取第二列并转换为浮点数
                    z.append(float(columns[2]))  # 提取第三列并转换为浮点数

    # 将列表转换为 NumPy 数组
    julian_dates_s = np.array(x)
    # julian_dates_o = np.round(julian_dates_s / 86400, 4)  # 转化为day
    julian_dates_o = julian_dates_s
    photon_fluxes_o = np.array(y)
    photon_fluxes_err = np.array(z)

    # 提取源名称 以'_'来分隔，若原数据不同，则可能会出现问题
    filename = os.path.basename(file_map)
    if len(filename.split("_")) >= 3:
        source_name = filename.split("_")[0] + "_" + filename.split("_")[1] + "_" + filename.split("_")[2]
    else:
        source_name = filename
    # 去掉错误数据如nan
    mask = ~np.isnan(julian_dates_o) & ~np.isnan(photon_fluxes_o)
    julian_dates = julian_dates_o[mask]
    photon_fluxes = photon_fluxes_o[mask]
    photon_fluxes_err = photon_fluxes_err[mask]

    if state is not None:
        state.setdefault('processed_files', []).append(filename)

    # print(julian_dates)
    # print(photon_fluxes)

    return source_name, julian_dates, photon_fluxes, photon_fluxes_err


import os
import numpy as np


def write_txt_data(filename, julian_dates, photon_fluxes, photon_fluxes_err, source_name=None, comment=None):
    """
    生成可被get_txt_data函数读取的txt文件

    参数:
    filename: 输出文件名
    julian_dates: 儒略日期数组
    photon_fluxes: 光子通量数组
    photon_fluxes_err: 光子通量误差数组
    source_name: 源名称（可选，用于生成文件名）
    comment: 文件头注释（可选）
    """

    # 确保目录存在
    os.makedirs(os.path.dirname(filename) if os.path.dirname(filename) else '.', exist_ok=True)

    with open(filename, 'w') as file:
        # 写入第一行（可以是注释或任意内容，因为读取时会跳过）
        if comment:
            file.write(f"# {comment}\n")
        else:
            file.write("# Data file generated by write_txt_data function\n")

        # 写入数据，每行三列
        for i in range(len(julian_dates)):
            line = f"{julian_dates[i]:.6f} {photon_fluxes[i]:.6f} {photon_fluxes_err[i]:.6f}\n"
            file.write(line)


# 使用示例
if __name__ == "__main__":
    # 示例数据
    julian_dates = [2450000.123456, 2450001.234567, 2450002.345678]
    photon_fluxes = [1.2345, 2.3456, 3.4567]
    photon_fluxes_err = [0.0123, 0.0234, 0.0345]

    # 写入文件
    write_txt_data(
        filename="example_source_2023_data.txt",
        julian_dates=julian_dates,
        photon_fluxes=photon_fluxes,
        photon_fluxes_err=photon_fluxes_err,
        comment="Example astronomical data - Julian dates, photon fluxes and errors"
    )
    # 测试读取
    source_name, julian_dates, photon_fluxes, photon_fluxes_err = get_txt_data("example_source_2023_data.txt", None)
    print(source_name, julian_dates, photon_fluxes, photon_fluxes_err)